version: "3.8"

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress-local-luvee
    volumes:
      - ./:/var/www/html
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      PHP_MEMORY_LIMIT: 1024M
      PHP_MAX_EXECUTION_TIME: 300
      PHP_MAX_INPUT_VARS: 5000
      PHP_POST_MAX_SIZE: 100M
      PHP_UPLOAD_MAX_FILESIZE: 100M

  wpcli:
    image: wordpress:cli
    container_name: wpcli-luvee
    depends_on:
      - wordpress
    volumes:
      - ./:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      PHP_MEMORY_LIMIT: 1024M
      PHP_MAX_EXECUTION_TIME: 300
    entrypoint: wp
